on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2 # Replace with your desired Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./data/requirements-api.txt  # Add any additional dependencies needed for testing
      - name: Run flask api Tests
        run: |
          python -m pytest ./tests/test-unit-api.py

   build-and-deploy:
    needs: test # Only runs if 'test' job passes
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry using Azure CLI
        run: |
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Build and Push Docker Image to ACR
        run: |
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/myfastapiapp:latest .
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/myfastapiapp:latest

      - name: Deploy to Azure Container Instance
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          name: myfastapiapp-container
          image: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/myfastapiapp:latest
          registry-login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          registry-username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          dns-name-label: myfastapiapp-label # Replace this with a unique label for your app URL
          ports: 8000
          location: francecentral # Set location to France Central
          cpu: 1
          memory: 1.5
          os-type: Linux
          protocol: TCP
          restart-policy: Always
