on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.2  # Replace with your desired Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./data/requirements-api.txt  # Add any additional dependencies needed for testing
    - name: Run flask api Tests
      run: |
        python -m pytest ./tests/test-unit-api.py